; Aircraft specific handler for FlightFactor 777-200ER aircraft
; created by https://github.com/CyberGuerro

log_level="ERROR"
aircraft_acf="777-200ER_xp12.acf"
script_file="ff777-xpanel-script.lua"
wait_for_available="1-sim/command/autobrakeSwitch_set_0"

;---------------------- Saitek Switch Panel -------------------------
[device:id="saitek_switch"]
vid="06a3"
pid="0d67"

;MAG
[button:id="MAG_OFF"]
on_push="commandref:1-sim/command/autobrakeSwitch_set_0:once"
[button:id="MAG_RIGHT"]
on_push="commandref:1-sim/command/autobrakeSwitch_set_1:once"
[button:id="MAG_LEFT"]
on_push="commandref:1-sim/command/autobrakeSwitch_set_3:once"
[button:id="MAG_BOTH"]
on_push="commandref:1-sim/command/autobrakeSwitch_set_5:once"
[button:id="ENG_START"]
on_push="commandref:1-sim/command/autobrakeSwitch_set_7:once"

;BATTERY
[button:id="BATTERY"]
on_push="commandref:1-sim/command/batteryButton_button:once"
on_release="commandref:1-sim/command/batteryButton_button:once"

;ALTERNATOR
[button:id="ALTERNATOR"]
on_push="lua:power('on')"
on_release="lua:power('off')"

;AVIONICS
[button:id="AVIONICS"]
on_push="commandref:1-sim/command/adiruSwitch_button:once"
on_release="commandref:1-sim/command/adiruSwitch_button:once"

;FUEL_PUMP
[button:id="FUEL_PUMP"]
on_push="commandref:1-sim/command/fuelLeftAftPumpSwitch_button:once"
on_push="commandref:1-sim/command/fuelLeftFwdPumpSwitch_button:once"
on_push="commandref:1-sim/command/fuelCenterLPumpSwitch_button:once"
on_push="commandref:1-sim/command/fuelCenterRPumpSwitch_button:once"
on_push="commandref:1-sim/command/fuelRightAftPumpSwitch_button:once"
on_push="commandref:1-sim/command/fuelRightFwdPumpSwitch_button:once"
on_release="commandref:1-sim/command/fuelLeftAftPumpSwitch_button:once"
on_release="commandref:1-sim/command/fuelLeftFwdPumpSwitch_button:once"
on_release="commandref:1-sim/command/fuelCenterLPumpSwitch_button:once"
on_release="commandref:1-sim/command/fuelCenterRPumpSwitch_button:once"
on_release="commandref:1-sim/command/fuelRightAftPumpSwitch_button:once"
on_release="commandref:1-sim/command/fuelRightFwdPumpSwitch_button:once"

;DE_ICE
[button:id="DE_ICE"]
on_push="commandref:1-sim/command/windowSideLeftSwitch_button:once"
on_push="commandref:1-sim/command/windowFwdLeftSwitch_button:once"
on_push="commandref:1-sim/command/windowFwdRightSwitch_button:once"
on_push="commandref:1-sim/command/windowSideRightSwitch_button:once"
on_release="commandref:1-sim/command/windowSideLeftSwitch_button:once"
on_release="commandref:1-sim/command/windowFwdLeftSwitch_button:once"
on_release="commandref:1-sim/command/windowFwdRightSwitch_button:once"
on_release="commandref:1-sim/command/windowSideRightSwitch_button:once"

;PITOT_HEAT
[button:id="PITOT_HEAT"]
; lo uso come alternativa per il Logo e Wing lights
on_push="commandref:1-sim/command/logoLightSwitch_button:once"
on_push="commandref:1-sim/command/wingLightSwitch_button:once"
on_release="commandref:1-sim/command/logoLightSwitch_button:once"
on_release="commandref:1-sim/command/wingLightSwitch_button:once"

;COWL_FLAPS
[button:id="COWL_FLAPS"]
on_push="commandref:1-sim/command/leftPackButton_button:once"
on_push="commandref:1-sim/command/rightPackButton_button:once"
on_release="commandref:1-sim/command/leftPackButton_button:once"
on_release="commandref:1-sim/command/rightPackButton_button:once"

;PANEL_LIGHTS
[button:id="PANEL_LIGHTS"]
on_push="commandref:1-sim/command/stormLightSwitch_button:once"
on_release="commandref:1-sim/command/stormLightSwitch_button:once"

;BEACON
[button:id="BEACON"]
on_push="commandref:1-sim/command/beaconLightSwitch_button:once"
on_release="commandref:1-sim/command/beaconLightSwitch_button:once"

;NAV
[button:id="NAV"]
on_push="commandref:1-sim/command/navLightSwitch_button:once"
on_release="commandref:1-sim/command/navLightSwitch_button:once"

;STROBE
[button:id="STROBE"]
on_push="commandref:1-sim/command/strobeLightSwitch_trigger:once"
on_release="commandref:1-sim/command/strobeLightSwitch_trigger:once"

;TAXI
[button:id="TAXI"]
on_push="commandref:1-sim/command/taxiLightSwitch_trigger:once"
on_push="commandref:1-sim/command/runwayTurnoffLeftSwitch_trigger:once"
on_push="commandref:1-sim/command/runwayTurnoffRightSwitch_trigger:once"
on_release="commandref:1-sim/command/taxiLightSwitch_trigger:once"
on_release="commandref:1-sim/command/runwayTurnoffLeftSwitch_trigger:once"
on_release="commandref:1-sim/command/runwayTurnoffRightSwitch_trigger:once"

;LANDING
[button:id="LANDING"]
on_push="commandref:1-sim/command/landingLightLeftSwitch_trigger:once"
on_push="commandref:1-sim/command/landingLightNoseSwitch_trigger:once"
on_push="commandref:1-sim/command/landingLightRightSwitch_trigger:once"
on_release="commandref:1-sim/command/landingLightLeftSwitch_trigger:once"
on_release="commandref:1-sim/command/landingLightNoseSwitch_trigger:once"
on_release="commandref:1-sim/command/landingLightRightSwitch_trigger:once"

;GEAR_UP
[button:id="GEAR_UP"]
on_push="commandref:sim/flight_controls/landing_gear_up:once"
;GEAR_DOWN
[button:id="GEAR_DOWN"]
on_push="commandref:sim/flight_controls/landing_gear_down:once"

;GHEAR LIGHTS
[light:id="GEAR_NOSE_GREEN"]
trigger_lit="lua:landing_light_green(0):1"
trigger_unlit="lua:landing_light_green(0):0"
[light:id="GEAR_LEFT_GREEN"]
trigger_lit="lua:landing_light_green(1):1"
trigger_unlit="lua:landing_light_green(1):0"
[light:id="GEAR_RIGHT_GREEN"]
trigger_lit="lua:landing_light_green(3):1"
trigger_unlit="lua:landing_light_green(3):0"
[light:id="GEAR_NOSE_RED"]
trigger_lit="lua:landing_light_red(0):1"
trigger_unlit="lua:landing_light_red(0):0"
[light:id="GEAR_LEFT_RED"]
trigger_lit="lua:landing_light_red(1):1"
trigger_unlit="lua:landing_light_red(1):0"
[light:id="GEAR_RIGHT_RED"]
trigger_lit="lua:landing_light_red(3):1"
trigger_unlit="lua:landing_light_red(3):0"
;--------------------------------------------------------------------

;---------------------- Saitek Radio Panel -------------------------
[device:id="saitek_radio"]
vid="6a3"
pid="d05"

[multi_display:id="RADIO_DISPLAY_ACTIVE_UP"]
line="on_select:SW_UP_COM1,dataref:sim/cockpit/radios/com1_freq_hz,dot_position:2"
line="on_select:SW_UP_COM2,dataref:sim/cockpit/radios/com2_freq_hz,dot_position:2"
line="on_select:SW_UP_NAV1,dataref:sim/cockpit/radios/nav1_freq_hz,dot_position:2"
line="on_select:SW_UP_NAV2,dataref:sim/cockpit/radios/nav2_freq_hz,dot_position:2"
line="on_select:SW_UP_ADF,lua:get_adf('sim/cockpit/radios/adf1_freq_hz'),dot_position:1,minimum_digit_number:4"
line="on_select:SW_UP_IDT,dataref:sim/cockpit/radios/transponder_code,minimum_digit_number:4"

[multi_display:id="RADIO_DISPLAY_STBY_UP"]
line="on_select:SW_UP_COM1,dataref:sim/cockpit/radios/com1_stdby_freq_hz,dot_position:2"
line="on_select:SW_UP_COM2,dataref:sim/cockpit/radios/com2_stdby_freq_hz,dot_position:2"
line="on_select:SW_UP_NAV1,dataref:sim/cockpit/radios/nav1_stdby_freq_hz,dot_position:2"
line="on_select:SW_UP_NAV2,dataref:sim/cockpit/radios/nav2_stdby_freq_hz,dot_position:2"
line="on_select:SW_UP_ADF,lua:get_adf('sim/cockpit/radios/adf1_stdby_freq_hz'),dot_position:1,minimum_digit_number:4"

[button:id="KNOB_UP_BIG_PLUS"]
on_push="on_select:SW_UP_COM1,commandref:sim/radios/stby_com1_coarse_up_833"
on_push="on_select:SW_UP_COM2,commandref:sim/radios/stby_com2_coarse_up_833"
on_push="on_select:SW_UP_NAV1,dataref:sim/cockpit/radios/nav1_stdby_freq_hz:100:0:15000"
on_push="on_select:SW_UP_NAV2,dataref:sim/cockpit/radios/nav2_stdby_freq_hz:100:0:15000"
on_push="on_select:SW_UP_ADF,dataref:sim/cockpit/radios/adf1_stdby_freq_hz:100:0:359"
on_push="on_select:SW_UP_IDT,dataref:sim/cockpit/radios/transponder_code:100:0:8888"

[button:id="KNOB_UP_BIG_MINUS"]
on_push="on_select:SW_UP_COM1,commandref:sim/radios/stby_com1_coarse_down_833"
on_push="on_select:SW_UP_COM2,commandref:sim/radios/stby_com2_coarse_down_833"
on_push="on_select:SW_UP_NAV1,dataref:sim/cockpit/radios/nav1_stdby_freq_hz:-100:0:16000"
on_push="on_select:SW_UP_NAV2,dataref:sim/cockpit/radios/nav2_stdby_freq_hz:-100:0:16000"
on_push="on_select:SW_UP_ADF,dataref:sim/cockpit/radios/adf1_stdby_freq_hz:-100:0:359"
on_push="on_select:SW_UP_IDT,dataref:sim/cockpit2/radios/actuators/transponder_code:-100:0:8888"

[button:id="KNOB_UP_SMALL_PLUS"]
on_push="on_select:SW_UP_COM1,commandref:sim/radios/stby_com1_fine_up_833"
on_push="on_select:SW_UP_COM2,commandref:sim/radios/stby_com2_fine_up_833"
on_push="on_select:SW_UP_NAV1,dataref:sim/cockpit/radios/nav1_stdby_freq_hz:1:0:15000"
on_push="on_select:SW_UP_NAV2,dataref:sim/cockpit/radios/nav2_stdby_freq_hz:1:0:15000"
on_push="on_select:SW_UP_ADF,dataref:sim/cockpit/radios/adf1_stdby_freq_hz:1:0:359"
on_push="on_select:SW_UP_IDT,dataref:sim/cockpit/radios/transponder_code:1:0:8888"

[button:id="KNOB_UP_SMALL_MINUS"]
on_push="on_select:SW_UP_COM1,commandref:sim/radios/stby_com1_fine_down_833"
on_push="on_select:SW_UP_COM2,commandref:sim/radios/stby_com2_fine_down_833"
on_push="on_select:SW_UP_NAV1,dataref:sim/cockpit/radios/nav1_stdby_freq_hz:-1:0:16000"
on_push="on_select:SW_UP_NAV2,dataref:sim/cockpit/radios/nav2_stdby_freq_hz:-1:0:16000"
on_push="on_select:SW_UP_ADF,dataref:sim/cockpit/radios/adf1_stdby_freq_hz:-1:0:359"
on_push="on_select:SW_UP_IDT,dataref:sim/cockpit2/radios/actuators/transponder_code:-1:0:8888"

[button:id="ACT_STBY_UP"]
on_push="on_select:SW_UP_COM1,commandref:sim/radios/com1_standy_flip:once"
on_push="on_select:SW_UP_COM2,commandref:sim/radios/com2_standy_flip:once"
on_push="on_select:SW_UP_NAV1,commandref:sim/radios/nav1_standy_flip:once"
on_push="on_select:SW_UP_NAV2,commandref:sim/radios/nav2_standy_flip:once"
on_push="on_select:SW_UP_ADF,commandref:sim/radios/adf1_standy_flip:once"



[multi_display:id="RADIO_DISPLAY_ACTIVE_DOWN"]
line="on_select:SW_DOWN_COM1,dataref:sim/cockpit/radios/com1_freq_hz,dot_position:2"
line="on_select:SW_DOWN_COM2,dataref:sim/cockpit/radios/com2_freq_hz,dot_position:2"
line="on_select:SW_DOWN_NAV1,dataref:sim/cockpit/radios/nav1_freq_hz,dot_position:2"
line="on_select:SW_DOWN_NAV2,dataref:sim/cockpit/radios/nav2_freq_hz,dot_position:2"
line="on_select:SW_DOWN_ADF,lua:get_adf('sim/cockpit/radios/adf1_freq_hz'),dot_position:1,minimum_digit_number:4"
line="on_select:SW_DOWN_DME,dataref:sim/cockpit/radios/nav1_dme_dist_m"
line="on_select:SW_DOWN_IDT,dataref:sim/cockpit/radios/transponder_code,minimum_digit_number:4"

[multi_display:id="RADIO_DISPLAY_STBY_DOWN"]
line="on_select:SW_DOWN_COM1,dataref:sim/cockpit/radios/com1_stdby_freq_hz,dot_position:2"
line="on_select:SW_DOWN_COM2,dataref:sim/cockpit/radios/com2_stdby_freq_hz,dot_position:2"
line="on_select:SW_DOWN_NAV1,dataref:sim/cockpit/radios/nav1_stdby_freq_hz,dot_position:2"
line="on_select:SW_DOWN_NAV2,dataref:sim/cockpit/radios/nav2_stdby_freq_hz,dot_position:2"
line="on_select:SW_DOWN_ADF,lua:get_adf('sim/cockpit/radios/adf1_stdby_freq_hz'),dot_position:1,minimum_digit_number:4"
line="on_select:SW_DOWN_DME,dataref:sim/cockpit/radios/nav2_dme_dist_m"

[button:id="KNOB_DOWN_BIG_PLUS"]
on_push="on_select:SW_DOWN_COM1,commandref:sim/radios/stby_com1_coarse_up_833"
on_push="on_select:SW_DOWN_COM2,commandref:sim/radios/stby_com2_coarse_up_833"
on_push="on_select:SW_DOWN_NAV1,dataref:sim/cockpit/radios/nav1_stdby_freq_hz:100:0:15000"
on_push="on_select:SW_DOWN_NAV2,dataref:sim/cockpit/radios/nav2_stdby_freq_hz:100:0:15000"
on_push="on_select:SW_DOWN_ADF,dataref:sim/cockpit/radios/adf1_stdby_freq_hz:100:0:359"
on_push="on_select:SW_DOWN_IDT,dataref:sim/cockpit/radios/transponder_code:100:0:8888"

[button:id="KNOB_DOWN_BIG_MINUS"]
on_push="on_select:SW_DOWN_COM1,commandref:sim/radios/stby_com1_coarse_down_833"
on_push="on_select:SW_DOWN_COM2,commandref:sim/radios/stby_com2_coarse_down_833"
on_push="on_select:SW_DOWN_NAV1,dataref:sim/cockpit/radios/nav1_stdby_freq_hz:-100:0:16000"
on_push="on_select:SW_DOWN_NAV2,dataref:sim/cockpit/radios/nav2_stdby_freq_hz:-100:0:16000"
on_push="on_select:SW_DOWN_ADF,dataref:sim/cockpit/radios/adf1_stdby_freq_hz:-100:0:359"
on_push="on_select:SW_DOWN_IDT,dataref:sim/cockpit2/radios/actuators/transponder_code:-100:0:8888"

[button:id="KNOB_DOWN_SMALL_PLUS"]
on_push="on_select:SW_DOWN_COM1,commandref:sim/radios/stby_com1_fine_up_833"
on_push="on_select:SW_DOWN_COM2,commandref:sim/radios/stby_com2_fine_up_833"
on_push="on_select:SW_DOWN_NAV1,dataref:sim/cockpit/radios/nav1_stdby_freq_hz:1:0:15000"
on_push="on_select:SW_DOWN_NAV2,dataref:sim/cockpit/radios/nav2_stdby_freq_hz:1:0:15000"
on_push="on_select:SW_DOWN_ADF,dataref:sim/cockpit/radios/adf1_stdby_freq_hz:1:0:359"
on_push="on_select:SW_DOWN_IDT,dataref:sim/cockpit/radios/transponder_code:1:0:8888"

[button:id="KNOB_DOWN_SMALL_MINUS"]
on_push="on_select:SW_DOWN_COM1,commandref:sim/radios/stby_com1_fine_down_833"
on_push="on_select:SW_DOWN_COM2,commandref:sim/radios/stby_com2_fine_down_833"
on_push="on_select:SW_DOWN_NAV1,dataref:sim/cockpit/radios/nav1_stdby_freq_hz:-1:0:16000"
on_push="on_select:SW_DOWN_NAV2,dataref:sim/cockpit/radios/nav2_stdby_freq_hz:-1:0:16000"
on_push="on_select:SW_DOWN_ADF,dataref:sim/cockpit/radios/adf1_stdby_freq_hz:-1:0:359"
on_push="on_select:SW_DOWN_IDT,dataref:sim/cockpit2/radios/actuators/transponder_code:-1:0:8888"

[button:id="ACT_STBY_DOWN"]
on_push="on_select:SW_DOWN_COM1,commandref:sim/radios/com1_standy_flip:once"
on_push="on_select:SW_DOWN_COM2,commandref:sim/radios/com2_standy_flip:once"
on_push="on_select:SW_DOWN_NAV1,commandref:sim/radios/nav1_standy_flip:once"
on_push="on_select:SW_DOWN_NAV2,commandref:sim/radios/nav2_standy_flip:once"
on_push="on_select:SW_DOWN_ADF,commandref:sim/radios/adf1_standy_flip:once"
;--------------------------------------------------------------------
